#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <inttypes.h>
#include <string.h>
#include <time.h>

#include "cli_rom.h"

int main()
{
  // setup initial rom
  CliRom_st cli_rom;
  int record;

  bzero((void *)&cli_rom, sizeof(CliRom_st));

  for (record=0; record < 0x20; record++)
  {
    sprintf(cli_rom.records[record].command_str, " %02d - reserved           ", record);

    cli_rom.records[record].default_idx = 0;
    cli_rom.records[record].start_idx = 0;
    cli_rom.records[record].value_idx = 0;
    cli_rom.records[record].num_values = 0;
  }

  for (; record < 0x80; record++)
  {
    sprintf(cli_rom.records[record].command_str, " %c - unused             ", record);
    cli_rom.records[record].default_idx = 0;
    cli_rom.records[record].start_idx = 0;
    cli_rom.records[record].value_idx = 0;
    cli_rom.records[record].num_values = 0;
  }

  sprintf(cli_rom.formatted_value, "format");



  // transfer banner txt file into ROM footpront
  //  TODO make sure dows not exceed 2048
  FILE *banner_file = fopen("banner.txt", "r");
  uint32_t pos=0;

  while (!feof(banner_file))
  {
    char *res = fgets(&cli_rom.banner[pos], 100, banner_file);
    if (res == NULL) break;
    pos += strlen(res);
    //cli_rom.banner[pos++] = 0x0a;
    cli_rom.banner[pos++] = 0x0d;
  }
  cli_rom.banner_len = pos;




  // transfer registers and register values into ROM footpront
  // TODO count register values for each command
  uint32_t line_no = 0;
  FILE *registers_file = fopen("registers.txt", "r");
  char delim[] = " \t\n\0";
  while (!feof(registers_file))
  {
    char *next_ptr = NULL;
    char next_line[100];

    // next line from registers file
    char *res = fgets(next_line, 100, registers_file);
    if (res == NULL) break;
    fprintf(stderr, "\n\n\nline %3u - %s\n", line_no++, next_line);

    // grab command character
    next_ptr = strtok(res, delim);
    if (next_ptr == NULL) continue;

    // assign command index
    uint8_t index = next_ptr[0];
    fprintf(stderr, "register hotkey %02x %c\n", index, index);

    // grab description
    next_ptr = strtok(NULL, delim);
    if (next_ptr == NULL) continue;

    fprintf(stderr, "register hotkey %02x %c - %s\n", index, index, next_ptr);

    // record description - TODO make sure does not exceed 16
    cli_rom.records[index].command_key = index;
    cli_rom.records[index].command_str[1] = ' ';
    sprintf(&cli_rom.records[index].command_str[2], next_ptr);

    // count constrained register values

  }



  // BUILD time
  {
    char zulu_time[25];
    time_t now;
    struct tm *gmt;

    // Get current system time
    time(&now);

    // Convert to UTC/GMT
    gmt = gmtime(&now);

    // Format into ISO 8601 Zulu format (YYYY-MM-DDTHH:MM:SSZ)
    strftime(zulu_time, sizeof(zulu_time), "%Y-%m-%dT%H:%M:%SZ", gmt);

    // Print the result
    fprintf(stderr, "Zulu Time: %s\n", zulu_time);

    strcpy(cli_rom.build_time, zulu_time);
  }


  // PROMPT
  sprintf(cli_rom.prompt, "dP_GPSDO> ");


  // write the hex bin ROM fooprint to file
  uint8_t *val = (uint8_t *)&cli_rom;
  for (int i=0; i < sizeof(CliRom_st); i++)
    fprintf(stdout, "%02x\n", val[i]);



  // generate a system verilog header for accessing ROM footprint

  FILE *svh = fopen("cli_rom.svh", "w");

  fprintf(svh, "`ifndef _CLI_ROM_SVH_\n");
  fprintf(svh, "`define _CLI_ROM_SVH_\n");
  fprintf(svh, "`define CLI_ROM_LEN %lu\n", sizeof(CliRom_st));
  fprintf(svh, "`define RECORD_LEN %lu\n", sizeof(CliRecord_st));
  fprintf(svh, "`define RECORD_POS %lu\n", (uint64_t) cli_rom.records - (uint64_t)&cli_rom);
  fprintf(svh, "`define BANNER_POS %lu\n", (uint64_t) cli_rom.banner - (uint64_t)&cli_rom);
  fprintf(svh, "`define BANNER_LEN %lu\n", (uint64_t) &cli_rom.banner_len - (uint64_t)&cli_rom);
  fprintf(svh, "`define PROMPT_POS %lu\n", (uint64_t) cli_rom.prompt - (uint64_t)&cli_rom);
  fprintf(svh, "`define PROMPT_LEN %lu\n", strlen(cli_rom.prompt));
  fprintf(svh, "`define BUILD_TIME_POS %lu\n", (uint64_t) cli_rom.build_time - (uint64_t)&cli_rom);
  fprintf(svh, "`define BUILD_TIME_LEN %lu\n", strlen(cli_rom.build_time));
  fprintf(svh, "`define BANNER_LEN %u\n", cli_rom.banner_len);
  fprintf(svh, "`define FORMATTED_POS %lu\n", (uint64_t) &cli_rom.formatted_value - (uint64_t)&cli_rom);
  fprintf(svh, "`define REGISTERS_POS %lu\n", (uint64_t) cli_rom.register_values - (uint64_t)&cli_rom);
  fprintf(svh, "`endif //_CLI_ROM_SVH_\n");
  fprintf(svh, "// cli_rom.svh - header generated by cli_rom.c\n");

  fclose(svh);
    
}
